-- 결제코드
INSERT INTO PAY_CD VALUES('01', '현금');
INSERT INTO PAY_CD VALUES('02', '카드');

-- 직책코드 
INSERT INTO POSITION_CD VALUES('01', '점장');
INSERT INTO POSITION_CD VALUES('02', '직원');

-- 배송코드
INSERT INTO DELIVERY_STATUS_CD VALUES('01', '집화처리');
INSERT INTO DELIVERY_STATUS_CD VALUES('02', '간선하차');
INSERT INTO DELIVERY_STATUS_CD VALUES('03', '터미널간선상차');
INSERT INTO DELIVERY_STATUS_CD VALUES('04', '간선하차');
INSERT INTO DELIVERY_STATUS_CD VALUES('05', '터미널간선하차');
INSERT INTO DELIVERY_STATUS_CD VALUES('06', '배달출발');
INSERT INTO DELIVERY_STATUS_CD VALUES('07', '배달완료');
INSERT INTO DELIVERY_STATUS_CD VALUES('08', '오배송');

-- 제품분류코드
INSERT INTO PRODUCT_TYPE_CD VALUES('001', '과자류');
INSERT INTO PRODUCT_TYPE_CD VALUES('002', '음료류');
INSERT INTO PRODUCT_TYPE_CD VALUES('003', '빵류');
INSERT INTO PRODUCT_TYPE_CD VALUES('004', '도시락류');
INSERT INTO PRODUCT_TYPE_CD VALUES('005', '냉동식품류');
INSERT INTO PRODUCT_TYPE_CD VALUES('006', '냉장식품류');
INSERT INTO PRODUCT_TYPE_CD VALUES('007', '커피류');
INSERT INTO PRODUCT_TYPE_CD VALUES('008', '일회용품류');
INSERT INTO PRODUCT_TYPE_CD VALUES('009', '당류');
INSERT INTO PRODUCT_TYPE_CD VALUES('010', '유제품류');
INSERT INTO PRODUCT_TYPE_CD VALUES('011', '주류');
INSERT INTO PRODUCT_TYPE_CD VALUES('012', '일회용품류');
INSERT INTO PRODUCT_TYPE_CD VALUES('013', '문구류');
INSERT INTO PRODUCT_TYPE_CD VALUES('014', '빙과류');
INSERT INTO PRODUCT_TYPE_CD VALUES('015', '기타');

-- 파손위험도코드
INSERT INTO DAMAGE_RISK_CD VALUES('01', '안전');
INSERT INTO DAMAGE_RISK_CD VALUES('02', '취급주의');