
CREATE TABLE CALCULATE
(
	CALCULATE_DT         VARCHAR2(10) NOT NULL ,
	CACULATE_WON         DECIMAL(19,4) NOT NULL ,
	REAL_CALCULATE_WON   DECIMAL(19,4) NOT NULL ,
	STAFF_NO             VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKCALCULATE ON CALCULATE
(CALCULATE_DT   ASC);



ALTER TABLE CALCULATE
	ADD CONSTRAINT  XPKCALCULATE PRIMARY KEY (CALCULATE_DT);



CREATE TABLE CUSTOMER
(
	CUSTOMER_NO          VARCHAR2(8) NOT NULL ,
	CUSTOMER_NM          VARCHAR2(20) NOT NULL ,
	MILEAGE              DECIMAL(19,4) NOT NULL ,
	CUSTOMER_SEX         CHAR(1) NULL ,
	CUSTOMER_AGE         INTEGER NULL 
);



CREATE UNIQUE INDEX XPKCUSTOMER ON CUSTOMER
(CUSTOMER_NO   ASC);



ALTER TABLE CUSTOMER
	ADD CONSTRAINT  XPKCUSTOMER PRIMARY KEY (CUSTOMER_NO);



CREATE TABLE DAMAGE_RISK_CD
(
	DAMAGE_RISK_CD       VARCHAR2(2) NOT NULL ,
	DAMAGE_RISK          VARCHAR2(20) NOT NULL 
);



CREATE UNIQUE INDEX XPKDAMAGE_RISK_CD ON DAMAGE_RISK_CD
(DAMAGE_RISK_CD   ASC);



ALTER TABLE DAMAGE_RISK_CD
	ADD CONSTRAINT  XPKDAMAGE_RISK_CD PRIMARY KEY (DAMAGE_RISK_CD);



CREATE TABLE DELIVERY
(
	DELIVERY_STAFF       VARCHAR2(20) NULL ,
	REQUEST_NO           VARCHAR2(8) NOT NULL ,
	DELIVERY_STATUS_START VARCHAR2(10) NULL ,
	DELIVERY_STATUS_END  VARCHAR2(10) NULL ,
	DELIVERY_STATUS_CD   CHAR(2) NOT NULL ,
	DELIVERY_NO          VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKDELIVERY ON DELIVERY
(DELIVERY_NO   ASC);



ALTER TABLE DELIVERY
	ADD CONSTRAINT  XPKDELIVERY PRIMARY KEY (DELIVERY_NO);



CREATE TABLE DELIVERY_STATUS_CD
(
	DELIVERY_STATUS_CD   CHAR(2) NOT NULL ,
	DELIVERY_STATUS      VARCHAR2(20) NOT NULL 
);



CREATE UNIQUE INDEX XPKDELIVERY_STATUS_CD ON DELIVERY_STATUS_CD
(DELIVERY_STATUS_CD   ASC);



ALTER TABLE DELIVERY_STATUS_CD
	ADD CONSTRAINT  XPKDELIVERY_STATUS_CD PRIMARY KEY (DELIVERY_STATUS_CD);



CREATE TABLE ITEM
(
	ITEM_NO              VARCHAR2(8) NOT NULL ,
	SHELFLIFT            DATE NOT NULL ,
	PRODUCT_NO           VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKITEM ON ITEM
(ITEM_NO   ASC);



ALTER TABLE ITEM
	ADD CONSTRAINT  XPKITEM PRIMARY KEY (ITEM_NO);



CREATE TABLE PAY_CD
(
	PAY_CD               CHAR(2) NOT NULL ,
	PAY                  VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKPAY_CD ON PAY_CD
(PAY_CD   ASC);



ALTER TABLE PAY_CD
	ADD CONSTRAINT  XPKPAY_CD PRIMARY KEY (PAY_CD);



CREATE TABLE POSITION_CD
(
	POSITION_CD          CHAR(2) NOT NULL ,
	POSITION             VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKPOSITION_CD ON POSITION_CD
(POSITION_CD   ASC);



ALTER TABLE POSITION_CD
	ADD CONSTRAINT  XPKPOSITION_CD PRIMARY KEY (POSITION_CD);



CREATE TABLE PRODUCT
(
	PRODUCT_NO           VARCHAR2(8) NOT NULL ,
	PRODUCT_NM           VARCHAR2(20) NOT NULL ,
	PRODUCT_WON          DECIMAL(19,4) NOT NULL ,
	DISCOUNT_RATE        NUMBER(2) NULL ,
	STOCK_CNT            NUMBER(8) NOT NULL ,
	PRODUCT_TYPE_CD      VARCHAR2(3) NOT NULL ,
	DAMAGE_RISK_CD       VARCHAR2(2) NOT NULL 
);



CREATE UNIQUE INDEX XPKPRODUCT ON PRODUCT
(PRODUCT_NO   ASC);



ALTER TABLE PRODUCT
	ADD CONSTRAINT  XPKPRODUCT PRIMARY KEY (PRODUCT_NO);



CREATE TABLE PRODUCT_TYPE_CD
(
	PRODUCT_TYPE_CD      VARCHAR2(3) NOT NULL ,
	PRODUCT_TYPE         VARCHAR2(20) NOT NULL 
);



CREATE UNIQUE INDEX XPKPRODUCT_TYPE_CD ON PRODUCT_TYPE_CD
(PRODUCT_TYPE_CD   ASC);



ALTER TABLE PRODUCT_TYPE_CD
	ADD CONSTRAINT  XPKPRODUCT_TYPE_CD PRIMARY KEY (PRODUCT_TYPE_CD);



CREATE TABLE REFUND
(
	REFUND_REASON        VARCHAR2(20) NULL ,
	ITEM_STATUS          VARCHAR2(20) NULL ,
	ITEM_NO              VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKREFUND ON REFUND
(ITEM_NO   ASC);



ALTER TABLE REFUND
	ADD CONSTRAINT  XPKREFUND PRIMARY KEY (ITEM_NO);



CREATE TABLE REQUEST
(
	REQUEST_NO           VARCHAR2(8) NOT NULL ,
	REQUEST_DT           DATE NOT NULL ,
	STAFF_NO             VARCHAR2(8) NOT NULL ,
	STORE_NO             VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKREQUEST ON REQUEST
(REQUEST_NO   ASC);



ALTER TABLE REQUEST
	ADD CONSTRAINT  XPKREQUEST PRIMARY KEY (REQUEST_NO);



CREATE TABLE REQUEST_LIST
(
	REQUEST_CNT          NUMBER(8) NOT NULL ,
	REQUEST_WON          DECIMAL(19,4) NOT NULL ,
	REQUEST_NO           VARCHAR2(8) NOT NULL ,
	PRODUCT_NO           VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKREQUEST_LIST ON REQUEST_LIST
(REQUEST_NO   ASC,PRODUCT_NO   ASC);



ALTER TABLE REQUEST_LIST
	ADD CONSTRAINT  XPKREQUEST_LIST PRIMARY KEY (REQUEST_NO,PRODUCT_NO);



CREATE TABLE RETURN
(
	RETURN_NO            VARCHAR2(8) NOT NULL ,
	RETURN_DT            DATE NOT NULL ,
	STAFF_NO             VARCHAR2(8) NOT NULL ,
	STORE_NO             VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKRETURN ON RETURN
(RETURN_NO   ASC);



ALTER TABLE RETURN
	ADD CONSTRAINT  XPKRETURN PRIMARY KEY (RETURN_NO);



CREATE TABLE RETURN_LIST
(
	RETURN_WON           DECIMAL(19,4) NOT NULL ,
	RETURN_REASON        VARCHAR2(20) NULL ,
	RETURN_NO            VARCHAR2(8) NOT NULL ,
	ITEM_NO              VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKRETURN_LIST ON RETURN_LIST
(ITEM_NO   ASC);



ALTER TABLE RETURN_LIST
	ADD CONSTRAINT  XPKRETURN_LIST PRIMARY KEY (ITEM_NO);



CREATE TABLE SALARY_RECORD
(
	SALARY_DATE          DATE NOT NULL ,
	SALARY_WON           DECIMAL(19,4) NOT NULL ,
	STAFF_NO             VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKSALARY_RECORD ON SALARY_RECORD
(STAFF_NO   ASC,SALARY_DATE   ASC);



ALTER TABLE SALARY_RECORD
	ADD CONSTRAINT  XPKSALARY_RECORD PRIMARY KEY (STAFF_NO,SALARY_DATE);



CREATE TABLE SALE
(
	SALE_NO              VARCHAR2(8) NOT NULL ,
	SALE_DT              VARCHAR2(10) NOT NULL ,
	SALE_WON             DECIMAL(19,4) NOT NULL ,
	RECEIVED_WON         DECIMAL(19,4) NOT NULL ,
	CUSTOMER_NO          VARCHAR2(8) NULL ,
	USED_MILEAGE         DECIMAL(19,4) NULL ,
	PAY_CD               CHAR(2) NOT NULL 
);



CREATE UNIQUE INDEX XPKSALE ON SALE
(SALE_NO   ASC);



ALTER TABLE SALE
	ADD CONSTRAINT  XPKSALE PRIMARY KEY (SALE_NO);



CREATE TABLE SALE_LIST
(
	SALE_NO              VARCHAR2(8) NOT NULL ,
	ITEM_NO              VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKSALE_LIST ON SALE_LIST
(SALE_NO   ASC,ITEM_NO   ASC);



ALTER TABLE SALE_LIST
	ADD CONSTRAINT  XPKSALE_LIST PRIMARY KEY (SALE_NO,ITEM_NO);



CREATE TABLE SALES
(
	SALES_DT             DATE NOT NULL ,
	INCOME               DECIMAL(19,4) NOT NULL ,
	SPENDING             DECIMAL(19,4) NOT NULL ,
	STAFF_NO             VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKSALES ON SALES
(SALES_DT   ASC);



ALTER TABLE SALES
	ADD CONSTRAINT  XPKSALES PRIMARY KEY (SALES_DT);



CREATE TABLE STAFF
(
	STAFF_NO             VARCHAR2(8) NOT NULL ,
	STAFF_NM             VARCHAR2(20) NOT NULL ,
	WORK_START_TIME      VARCHAR2(10) NULL ,
	WORK_END_TIME        VARCHAR2(10) NULL ,
	SALARY               DECIMAL(19,4) NULL ,
	EMPLOY_DATE          DATE NULL ,
	DISCHARGE_DATE       DATE NULL ,
	ACCOUNT_NO           NUMBER(20) NULL ,
	POSITION_CD          CHAR(2) NOT NULL ,
	PASSWORD             VARCHAR2(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKSTAFF ON STAFF
(STAFF_NO   ASC);



ALTER TABLE STAFF
	ADD CONSTRAINT  XPKSTAFF PRIMARY KEY (STAFF_NO);



CREATE TABLE STORE
(
	STORE_NO             VARCHAR2(8) NOT NULL ,
	STORE_LOC            VARCHAR2(50) NOT NULL ,
	STAFF_NO             VARCHAR2(8) NOT NULL 
);



CREATE UNIQUE INDEX XPKSTORE ON STORE
(STORE_NO   ASC);



ALTER TABLE STORE
	ADD CONSTRAINT  XPKSTORE PRIMARY KEY (STORE_NO);



ALTER TABLE CALCULATE
	ADD (CONSTRAINT R_15 FOREIGN KEY (STAFF_NO) REFERENCES STAFF (STAFF_NO));



ALTER TABLE DELIVERY
	ADD (CONSTRAINT R_23 FOREIGN KEY (REQUEST_NO) REFERENCES REQUEST (REQUEST_NO));



ALTER TABLE DELIVERY
	ADD (CONSTRAINT R_24 FOREIGN KEY (DELIVERY_STATUS_CD) REFERENCES DELIVERY_STATUS_CD (DELIVERY_STATUS_CD));



ALTER TABLE ITEM
	ADD (CONSTRAINT R_32 FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT (PRODUCT_NO));



ALTER TABLE PRODUCT
	ADD (CONSTRAINT R_27 FOREIGN KEY (PRODUCT_TYPE_CD) REFERENCES PRODUCT_TYPE_CD (PRODUCT_TYPE_CD));



ALTER TABLE PRODUCT
	ADD (CONSTRAINT R_31 FOREIGN KEY (DAMAGE_RISK_CD) REFERENCES DAMAGE_RISK_CD (DAMAGE_RISK_CD));



ALTER TABLE REFUND
	ADD (CONSTRAINT R_19 FOREIGN KEY (ITEM_NO) REFERENCES ITEM (ITEM_NO));



ALTER TABLE REQUEST
	ADD (CONSTRAINT R_8 FOREIGN KEY (STAFF_NO) REFERENCES STAFF (STAFF_NO));



ALTER TABLE REQUEST
	ADD (CONSTRAINT R_17 FOREIGN KEY (STORE_NO) REFERENCES STORE (STORE_NO));



ALTER TABLE REQUEST_LIST
	ADD (CONSTRAINT R_4 FOREIGN KEY (REQUEST_NO) REFERENCES REQUEST (REQUEST_NO));



ALTER TABLE REQUEST_LIST
	ADD (CONSTRAINT R_5 FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT (PRODUCT_NO));



ALTER TABLE RETURN
	ADD (CONSTRAINT R_9 FOREIGN KEY (STAFF_NO) REFERENCES STAFF (STAFF_NO));



ALTER TABLE RETURN
	ADD (CONSTRAINT R_18 FOREIGN KEY (STORE_NO) REFERENCES STORE (STORE_NO));



ALTER TABLE RETURN_LIST
	ADD (CONSTRAINT R_10 FOREIGN KEY (RETURN_NO) REFERENCES RETURN (RETURN_NO));



ALTER TABLE RETURN_LIST
	ADD (CONSTRAINT R_11 FOREIGN KEY (ITEM_NO) REFERENCES ITEM (ITEM_NO));



ALTER TABLE SALARY_RECORD
	ADD (CONSTRAINT R_20 FOREIGN KEY (STAFF_NO) REFERENCES STAFF (STAFF_NO));



ALTER TABLE SALE
	ADD (CONSTRAINT R_25 FOREIGN KEY (CUSTOMER_NO) REFERENCES CUSTOMER (CUSTOMER_NO) ON DELETE SET NULL);



ALTER TABLE SALE
	ADD (CONSTRAINT R_29 FOREIGN KEY (PAY_CD) REFERENCES PAY_CD (PAY_CD));



ALTER TABLE SALE_LIST
	ADD (CONSTRAINT R_12 FOREIGN KEY (SALE_NO) REFERENCES SALE (SALE_NO));



ALTER TABLE SALE_LIST
	ADD (CONSTRAINT R_13 FOREIGN KEY (ITEM_NO) REFERENCES ITEM (ITEM_NO));



ALTER TABLE SALES
	ADD (CONSTRAINT R_28 FOREIGN KEY (STAFF_NO) REFERENCES STAFF (STAFF_NO));



ALTER TABLE STAFF
	ADD (CONSTRAINT R_30 FOREIGN KEY (POSITION_CD) REFERENCES POSITION_CD (POSITION_CD));



ALTER TABLE STORE
	ADD (CONSTRAINT R_16 FOREIGN KEY (STAFF_NO) REFERENCES STAFF (STAFF_NO));


